### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by ghost** [Dariasteam/Geode#2]
Parser Error: Function signature doesn't match the parent. Parent signature is: 'void draw_polygon(PoolVector2Array, PoolColorArray, PoolVector2Array=default, Texture, Texture, bool)'.

plot.gd:36

**Comment by Dariasteam** [comment]
Hi! What version of godot are you using? This was created using an unstable version of 3.0 and I know some things have changed since then

**Comment by LinuxUserGD** [comment]
I'm using Godot master (https://github.com/godotengine/godot/commit/b902a2f2a7438810cdcb053568ed5c27089b1e8a)

**Comment by LinuxUserGD** [comment]
@Dariasteam Do you have a fix?
